### ISSUE TITLE
モデルのファイル

### ISSUE THREAD

**Issue by Vencenter** [Hiroshiba/hihobot-synthesis#2]
hihobot-synthesis\sample\model_duration_200
hihobot-synthesis\sample\model_acoustic_350

これらのモデルはどのファイルで生成されますか。すみません、ずっと探せてないので、教えていただけませんか。
たのんで、お願いいたします

**Comment by Hiroshiba** [comment]
READMEに書いてある通り、[こちら](https://r9y9.github.io/nnmnkwii/v0.0.1/nnmnkwii_gallery/notebooks/tts/02-Bidirectional-LSTM%20based%20RNNs%20for%20speech%20synthesis%20(en).html)で作成できます。
